language: ruby

rvm:
  - 2.0.0
  - 2.1
  - 2.2.3
  - 2.3.0

gemfile:
  - Gemfile

matrix:
  exclude:
    - rvm: 2.0.0
      gemfile: Gemfile

before_install:
  - gem update bundler

script: 'bundle exec rake test'
